### ISSUE TITLE
[FIX] EmotionDTO에 description을 추가하는 제안

### ISSUE THREAD

**Issue by pius338** [NewMillenniumWorkout/A-Neuk-BE-Server#17]
![스크린샷 2024-11-25 오후 8 20 58](https://github.com/user-attachments/assets/affb02eb-a268-4cf4-b36c-7361feeea4d1)

<img width="456" alt="KakaoTalk_Photo_2024-11-25-20-19-13" src="https://github.com/user-attachments/assets/7af152d6-3829-42e1-9c95-a755b23d6a2c">

이 부분에서 example만 오게 되어있는데 감정 선택 페이지 UI상 뜻과 예문을 함께 띄워줘야해서 description도 함께 오면 좋을 것 같아요

- 감정 선택 UI
![스크린샷 2024-11-25 오후 8 22 26](https://github.com/user-attachments/assets/216622fe-1b08-4cd2-94b9-1746beb991fa)

**Comment by LUCETE012** [comment]
추가하겠습니다~

@minseok128 디비에 description 추가해주세요 ! sql문 다시 받으면 코드 수정하겠습니당
